
print("Hola, digame su nombre porfavor")
nombre=input()
print("Dime tu edad")
edad=input()
print("Hola "+ nombre + ", tu edad es: "+ edad + ".")
print("De donde eres?")
nacimiento=input()
print("Y cuando nacistes?")
año=input()
print("Genial! eres de "+ nacimiento + " y nacistes el: "+ año + ".")
print("Cuentame mas, que edad tiene tu madre?")
madre=input()
numero1=int(madre)
print("Y tu padre?")
padre=input()
numero2=int(padre)
print("Sabias que los dos juntos suman: ", numero1 + numero2, " , interesante verdad?")
print("Ahora prueba mi calculadora")
print("Primer numero:")
Primer=input()
numerox=int(Primer)
print("Segundo numero")
Segundo=input()
numeroy=int(Segundo)
print("La suma es:", numerox + numeroy ,)
print("La resta es:", numerox - numeroy ,)
print("La multiplicacion es:", numerox * numeroy ,)
print("La division es:", numerox / numeroy ,)
print("El modulo es:", numerox % numeroy ,)
print("Bueno, ya has visto lo bien que funciona, ahora voy a calcular el area de un cuadrado.")
print("Introduce la base:")
base=input()
base=int(base1)
print("Ahora la altura:")
altura=input()
altura=int(altura1)
print("Area: ", nbase1)