print("Pon las variables:")
print("A:")
A=input()
num1=int(A)
print("B:")
B=input()
num2=int(B)
print("C:")
C=input()
num3=int(C)
print("D:")
D=input()
num4=int(D)
print("x:")
X=input()
inc=int(X)
print("Resultat: ", num1 + num2 * inc + num3 * inc**2 + num4 * inc**3 )