print("Quants refrescos de cola han comprat?")
cola=input()
producte1=int(cola)
print("De taronja?")
taro=input()
producte2=int(taro)
print("De llimona?")
llim=input()
producte3=int(llim)
print("-----------------------------------------------------------------------")
print("")
print("Producte Vendes Preu Total")
print("")
print("------------------------------------------------------------------------")
print("")
print("Cola", cola ,"0'17", round(producte1 * 0.17) )
print("Taronja", taro ,"0'20", round(producte2 * 0.20) )
print("Llimona", llim ,"0'19", round(producte3 * 0.19) )
print("Total:", round(0.17 * producte1 + 0.20 * producte2 + 0.19 * producte3) )